//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMMPGuiApp.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_ja_JPtest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ja_JPtest() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMMPGuiApp.Properties.Resources.ja-JPtest", typeof(Resources_ja_JPtest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   PocketMine-MPを使用するにはライセンスに同意する必要があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AcceptLicense {
            get {
                return ResourceManager.GetString("AcceptLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同意しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Agree {
            get {
                return ResourceManager.GetString("Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すでにPMMPが起動しているようです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AlreadyExecutePMMP {
            get {
                return ResourceManager.GetString("AlreadyExecutePMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロードが進行中です。強制終了しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmDownloadProgress {
            get {
                return ResourceManager.GetString("ConfirmDownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PMMPを強制終了しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmKillPMMP {
            get {
                return ResourceManager.GetString("ConfirmKillPMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バッチファイルダウンロード中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadBath {
            get {
                return ResourceManager.GetString("DownloadBath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バイナリダウンロード中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadBin {
            get {
                return ResourceManager.GetString("DownloadBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   composer関連ファイルダウンロード中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadComposer {
            get {
                return ResourceManager.GetString("DownloadComposer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在PMMPダウンロード中です。しばらくお待ち下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadingPMMP {
            get {
                return ResourceManager.GetString("DownloadingPMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PocketMine-MPダウンロード中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadPMMP {
            get {
                return ResourceManager.GetString("DownloadPMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集(_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   英語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PMMPを起動する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecutePMMP {
            get {
                return ResourceManager.GetString("ExecutePMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windowsランタイムインストーラーが起動します。手動でのインストールをお願いします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecuteRuntime {
            get {
                return ResourceManager.GetString("ExecuteRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バイナリの解凍中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExtractBin {
            get {
                return ResourceManager.GetString("ExtractBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最初 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最新情報を取得 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetLatestInfo {
            get {
                return ResourceManager.GetString("GetLatestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インストールが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InstallComplete {
            get {
                return ResourceManager.GetString("InstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   composerインストール中...... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InstallComposer {
            get {
                return ResourceManager.GetString("InstallComposer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PocketMine-MPをインストールします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InstallPMMP {
            get {
                return ResourceManager.GetString("InstallPMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーエンジンを入れる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IntroducingCustomServerEngine {
            get {
                return ResourceManager.GetString("IntroducingCustomServerEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタムサーバーエンジンを導入しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IntroducingTheCustomServerEngine {
            get {
                return ResourceManager.GetString("IntroducingTheCustomServerEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   導入 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PMMPを強制終了します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KillingPMMP {
            get {
                return ResourceManager.GetString("KillingPMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーを強制終了する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KillPMMP {
            get {
                return ResourceManager.GetString("KillPMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最後 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This program is free software: you can redistribute it and/or modify
        ///it under the terms of the GNU Lesser General Public License as published by
        ///the Free Software Foundation, either version 3 of the License, or
        ///(at your option) any later version. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次&gt;&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライセンスに同意しないとこのソフトウェアを使用することはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotAgreeLicense {
            get {
                return ResourceManager.GetString("NotAgreeLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [PMMPを停止する]を押さないと一部データが保存されません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotBeSavedforPMMPisRunning {
            get {
                return ResourceManager.GetString("NotBeSavedforPMMPisRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在PMMPをダウンロード中です。ダウンロードが終わったら検索することができます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotDownloadforDownloading {
            get {
                return ResourceManager.GetString("NotDownloadforDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PMMP実行中にはダウンロードできません。PMMPを停止してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotDownloadforPMMPisRunning {
            get {
                return ResourceManager.GetString("NotDownloadforPMMPisRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   32bitのwindowsではPMMPを動かすことができません！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotExecute32bit {
            get {
                return ResourceManager.GetString("NotExecute32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PMMPが起動していません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotExecutePMMP {
            get {
                return ResourceManager.GetString("NotExecutePMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PMMP実行時にはインストールできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotInstall_PMMPisRunning {
            get {
                return ResourceManager.GetString("NotInstall_PMMPisRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーエンジンの名前は&quot;PocketMine-MP.phar&quot;のみ有効です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotMatchServerEngineFileName {
            get {
                return ResourceManager.GetString("NotMatchServerEngineFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他(_O) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pharファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PharFile {
            get {
                return ResourceManager.GetString("PharFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ファイル(F)] から [PMMPをインストールする] を選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PleaseInstallPMMP {
            get {
                return ResourceManager.GetString("PleaseInstallPMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [実行(R)]から[サーバーを強制終了する]をクリックしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PleaseKillPMMP {
            get {
                return ResourceManager.GetString("PleaseKillPMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動ボタンを押して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PleasePressExecuteButton {
            get {
                return ResourceManager.GetString("PleasePressExecuteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プラグインを選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PleaseSelectPlugin {
            get {
                return ResourceManager.GetString("PleaseSelectPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プラグイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Plugin {
            get {
                return ResourceManager.GetString("Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PMMP起動中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PMMPExecuteNow {
            get {
                return ResourceManager.GetString("PMMPExecuteNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PMMPをインストール/アップデートする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PMMPInstallAndUpdate {
            get {
                return ResourceManager.GetString("PMMPInstallAndUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在PMMPダウンロード中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PMMPInstallNow {
            get {
                return ResourceManager.GetString("PMMPInstallNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PMMPが存在していません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PMMPNotFound {
            get {
                return ResourceManager.GetString("PMMPNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   定期的に[ファイル(F)]→[最新情報を取得]で更新を行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PoggitDefaultLabel {
            get {
                return ResourceManager.GetString("PoggitDefaultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;&lt;前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行(_R) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PMMPが実行中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RunningPMMP {
            get {
                return ResourceManager.GetString("RunningPMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インターネットから探す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchFormTheInternet {
            get {
                return ResourceManager.GetString("SearchFormTheInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MCBEForumから探す(日本語) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchMCBEForum {
            get {
                return ResourceManager.GetString("SearchMCBEForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   poggitから探す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchPoggit {
            get {
                return ResourceManager.GetString("SearchPoggit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   poggitから探す(英語) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchPoggitMenuItem {
            get {
                return ResourceManager.GetString("SearchPoggitMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jpn に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ローカルファイルから選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectLocalFile {
            get {
                return ResourceManager.GetString("SelectLocalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PMMPが正常に終了しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoppedPMMP {
            get {
                return ResourceManager.GetString("StoppedPMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PMMP停止処理中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoppingPMMPNow {
            get {
                return ResourceManager.GetString("StoppingPMMPNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PMMPを停止する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StopPMMP {
            get {
                return ResourceManager.GetString("StopPMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツール(_T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロード数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TurnDownload {
            get {
                return ResourceManager.GetString("TurnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TurnName {
            get {
                return ResourceManager.GetString("TurnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートは10秒ほど、インストールは5分程かかります に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateAndInstallTime {
            get {
                return ResourceManager.GetString("UpdateAndInstallTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VersionInfomation {
            get {
                return ResourceManager.GetString("VersionInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクスプローラーで表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewExproler {
            get {
                return ResourceManager.GetString("ViewExproler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   しばらくお待ち下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WaitAMinutes {
            get {
                return ResourceManager.GetString("WaitAMinutes", resourceCulture);
            }
        }
    }
}
