//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMMPGuiApp.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMMPGuiApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   It looks like PMMP is already running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AlreadyExecutePMMP {
            get {
                return ResourceManager.GetString("AlreadyExecutePMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download is in progress. Do you want to force quit? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmDownloadProgress {
            get {
                return ResourceManager.GetString("ConfirmDownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to kill PMMP? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmKillPMMP {
            get {
                return ResourceManager.GetString("ConfirmKillPMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloading batch file... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadBath {
            get {
                return ResourceManager.GetString("DownloadBath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloading binary... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadBin {
            get {
                return ResourceManager.GetString("DownloadBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloading files related to composer... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadComposer {
            get {
                return ResourceManager.GetString("DownloadComposer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The PMMP is currently being downloaded. Please wait for a while. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadingPMMP {
            get {
                return ResourceManager.GetString("DownloadingPMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloading PocketMine-MP now... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadPMMP {
            get {
                return ResourceManager.GetString("DownloadPMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit(_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start PMMP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecutePMMP {
            get {
                return ResourceManager.GetString("ExecutePMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Windows Runtime Installer will launch. Please install the software manually. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecuteRuntime {
            get {
                return ResourceManager.GetString("ExecuteRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decompressing binary... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExtractBin {
            get {
                return ResourceManager.GetString("ExtractBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Installation is now complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InstallComplete {
            get {
                return ResourceManager.GetString("InstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Installing composer...... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InstallComposer {
            get {
                return ResourceManager.GetString("InstallComposer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Install PocketMine-MP. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InstallPMMP {
            get {
                return ResourceManager.GetString("InstallPMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Include the server engine. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IntroducingCustomServerEngine {
            get {
                return ResourceManager.GetString("IntroducingCustomServerEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A custom server engine has been installed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IntroducingTheCustomServerEngine {
            get {
                return ResourceManager.GetString("IntroducingTheCustomServerEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   introduction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kill PMMP. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KillingPMMP {
            get {
                return ResourceManager.GetString("KillingPMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Force the server to close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KillPMMP {
            get {
                return ResourceManager.GetString("KillPMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you do not press [Stop PMMP], some data will not be saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotBeSavedforPMMPisRunning {
            get {
                return ResourceManager.GetString("NotBeSavedforPMMPisRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You cannot download while PMMP is running; please stop PMMP. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotDownloadforPMMPisRunning {
            get {
                return ResourceManager.GetString("NotDownloadforPMMPisRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I can&apos;t run PMMP on 32bit windows! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotExecute32bit {
            get {
                return ResourceManager.GetString("NotExecute32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PMMP is not running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotExecutePMMP {
            get {
                return ResourceManager.GetString("NotExecutePMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It cannot be installed when PMMP is executed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotInstall_PMMPisRunning {
            get {
                return ResourceManager.GetString("NotInstall_PMMPisRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The only valid server engine name is &quot;PocketMine-MP.phar&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotMatchServerEngineFileName {
            get {
                return ResourceManager.GetString("NotMatchServerEngineFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other(_O) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PharFile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PharFile {
            get {
                return ResourceManager.GetString("PharFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select [File(_F)] &gt; [Install PMMP] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PleaseInstallPMMP {
            get {
                return ResourceManager.GetString("PleaseInstallPMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select [Run(_R)] &gt; [Force the server to close]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PleaseKillPMMP {
            get {
                return ResourceManager.GetString("PleaseKillPMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press the Start button. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PleasePressExecuteButton {
            get {
                return ResourceManager.GetString("PleasePressExecuteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a plugin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PleaseSelectPlugin {
            get {
                return ResourceManager.GetString("PleaseSelectPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plugin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Plugin {
            get {
                return ResourceManager.GetString("Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PMMP is running... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PMMPExecuteNow {
            get {
                return ResourceManager.GetString("PMMPExecuteNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Install/update PMMP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PMMPInstallAndUpdate {
            get {
                return ResourceManager.GetString("PMMPInstallAndUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PMMP does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PMMPNotFound {
            get {
                return ResourceManager.GetString("PMMPNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run(_R) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PMMP is running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RunningPMMP {
            get {
                return ResourceManager.GetString("RunningPMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search from the internet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchFormTheInternet {
            get {
                return ResourceManager.GetString("SearchFormTheInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search by MCBEForum (Japanese) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchMCBEForum {
            get {
                return ResourceManager.GetString("SearchMCBEForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search from poggit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchPoggit {
            get {
                return ResourceManager.GetString("SearchPoggit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search from poggit{English) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchPoggitMenuItem {
            get {
                return ResourceManager.GetString("SearchPoggitMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seconds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   eng に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select from local files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectLocalFile {
            get {
                return ResourceManager.GetString("SelectLocalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StopPMMP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StopPMMP {
            get {
                return ResourceManager.GetString("StopPMMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tools(_T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update will take about 10 seconds, installation will take about 5 minutes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateAndInstallTime {
            get {
                return ResourceManager.GetString("UpdateAndInstallTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VersionInfomation {
            get {
                return ResourceManager.GetString("VersionInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View in Explorer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewExproler {
            get {
                return ResourceManager.GetString("ViewExproler", resourceCulture);
            }
        }
    }
}
